#! /bin/bash

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#このコマンドは以下のコマンドに依存します。
#・w3m
#・nkf
#ということで、上記のコマンドが動かせるように各自対応したものをインストールしておいてください。(w3mに関しては各自好みのブラウザを指定するように書き換えてもらって構いません) また、このコマンドは隠しファイルとして、"~/.wikiwiki/query/query.txt"をつくります。
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#"mkdir -p"でディレクトリがなければ２階層すべて作り、あれば無視します。
mkdir -p ~/.wikiwiki/query

#"touch"でquery.txtをつくります。あれば無視します。
touch ~/.wikiwiki/query/query.txt

#"echo"で$1,$2を出力し、それを"sed"でwikiwikiコマンドのオプション($1)は除外し、入力された言葉($2)だけにし、$2を"nkf"でURLエンコードし、"tr"でエンコードされた後の$2に含まれる"="を全て"%"に置換したものを、~/.wikiwiki/query/query.txtに書き込みます。(もしくは、上書きします。)
echo $1 $2 | sed "s/$1 $2/$2/g" | nkf -wMQ | tr = % > ~/.wikiwiki/query/query.txt

#「"cat"で~/.wikiwiki/query/query.txtの内容をそのまま標準出力に出力する」wi、ということを"txt"という変数に指定します。
txt=`cat ~/.wikiwiki/query/query.txt`

#"$txt"に"txt"で指定したファイルの内容を代入しページを出力します。
wikiwiki="w3m https://ja.wikipedia.org/wiki/"$txt""

#以下は、wikiwikiコマンドのオプション指定です。
while getopts CmWbqSsnvdacwAyuh option 
do
 case $option in
    C)
      wikiwiki="w3m https://commons.wikimedia.org/wiki/"$txt"?uselang=ja";;    
    m)
      wikiwiki="w3m https://meta.wikimedia.org/wiki/"$txt"";;
    W)
      wikiwiki="w3m https://ja.wiktionary.org/wiki/"$txt"";;
    b)
      wikiwiki="w3m https://ja.wikibooks.org/wiki/"$txt"";;
    q)
      wikiwiki="w3m https://ja.wikiquote.org/wiki/"$txt"";;
    S)
      wikiwiki="w3m https://ja.wikisource.org/wiki/"$txt"";;
    s)
      wikiwiki="w3m https://species.wikimedia.org/wiki/"$txt"";;
    n)
      wikiwiki="w3m https://ja.wikinews.org/wiki/"$txt"";;
    v)
      wikiwiki="w3m https://ja.wikiversity.org/wiki/"$txt"";;
    d)
      wikiwiki="w3m https://www.wikidata.org/wiki/"$txt"";;
    a)
      wikiwiki="w3m http://ansaikuropedia.org/wiki/"$txt"";;
    c)
      wikiwiki="w3m https://wiki.chakuriki.net/index.php/";;
    w)
      wikiwiki="w3m http://ja.starwars.wikia.com/wiki/"$txt"";;
    u)
      wikiwiki="w3m https://wiki.ubuntulinux.jp/";;
    A)
      wikiwiki="w3m http://ja.anime.wikia.com/wiki/"$txt"";;
    y)
      wikiwiki="w3m http://yaruo.wikia.com/wiki/"$txt"";;
    h)
      echo "wikiwikiコマンドで使えるオプションについては以下の通りです。

オプション指定無し - ウィキペディアを表示します。
[-C] - ウィキペディア・コモンズを表示します。
[-m] - メタウィキを表示します。
[-W] - ウィクショナリーを表示します。
[-b] - ウィキブックスを表示します。
[-q] - ウィキクォートを表示します。
[-S] - ウィキソースを表示します。
[-s] - ウィキスピーシーズを表示します。
[-n] - ウィキニュースを表示します。
[-v] - ウィキバーシティを表示します。
[-d] - ウィキデータを表示します。
[-a] - アンサイクロペディアを表示します。
[-c] - chakuwikiを表示します。
[-w] - Wookieepediaを表示します。
[-A] - Anipediaを表示します。
[-y] - やる夫 Wikiを表示します。
[-u] - Ubuntu Japanese Wikiを表示します。
[-h] - ヘルプを表示します。

また、検索したい言葉を、"wikiwiki [オプション] [検索したい言葉]"のようにするとオプションに対応したページでの検索結果が閲覧できます。"
      exit 1;;
    \?)
      echo "Usage: wikiwiki [-m] [-C] [-W] [-b] [-q] [-S] [-s] [-n] [-v] [-d] [-u] [-c] [-w] [-A] [-y] [-h]"
      exit 1;;
   esac
done
$wikiwiki
